

FROM nginx
COPY nginx.conf.qa /etc/nginx/nginx.conf
COPY dist /usr/share/nginx/html

COPY ./ssl/fullchain.pem /usr/ssl/pub/fullchain.pem
COPY ./ssl/privkey.pem /usr/ssl/priv/private.pem
COPY ./ssl/private-key-pwds.txt /usr/ssl/priv/private-key-pwds.txt

RUN chmod 644 /usr/ssl/pub/*.pem \
  && chmod 640 /usr/ssl/priv/*.pem\
  && chmod 640 /usr/ssl/priv/private-key-pwds.txt

